version: 2.1
jobs:
    #ESTE JOB ES PARA PRE-INSTALAR TODAS LAS DEPENDENCIAS
    #ANTES DE HACER LAS PRUEBAS UNITARIAS
    prebuild:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package-lock.json" }}
                - v1-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v1-dependencies-{{ checksum "package-lock.json" }}
                paths:
                    - node_modules
            - run:
                name: Testing
                command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
            
            - setup_remote_docker:
                version: 19.03.13
                

            # build and push Docker image
            - run: |
                TAG=0.1.$CIRCLE_BUILD_NUM
                docker build -t byronjl2003/angularpro:$TAG .
                echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                docker push byronjl2003/angularpro:$TAG           
                
    deploy:
        docker:
        - image: circleci/python:3.7
        steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
                pip install ecs-deploy
        - run:
            name: Deploy
            command: |
                ecs deploy $ECS_CLUSTER_NAME $ECS_SERVICE --image website-service trambocloud/nginx:latest --timeout 1200 --ignore-warnings --region $AWS_REGION

orbs:
  docker: circleci/docker@1.4.0
workflows:
    version: 2
    test:
        jobs:
            - prebuild
      
    #test:
    